# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title : "Jona fährt Fahrrad"
email: "jonabuck2@gmail.com"
description: >- # this means to ignore newlines until "baseurl:"
  Hi, ich versuche mit dem Fahrrad von Passau nach Istanbul zu fahren. Vielleicht funktioniert es.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https:\\jonabuck.me" # the base hostname & protocol for your site, e.g. http://example.com

timezone              : Europe/Berlin
#locale: de

# Build settings
theme: minimal-mistakes-jekyll

show_date: true

author:
  name                : "Jona"
  avatar              : "/assets/images/default/bio-photo.jpg"
  bio                 : "Hi, Ich versuche mit dem Fahrrad von Passau nach Istanbul zu fahren. Vielleicht funktioniert es. \n Diese Seite ist hauptsächlich als Tagebuch für mich gedacht und damit Familie und Freunde sehen können was ich gerade so mache :)"
  location            : "Hessen, Deutschland"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      show_date: true
